version: '3.8'

services:
  # app:
  #   container_name: app-container
  #   build: ./
  #   command: npm run start:migrate
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSW}@postgres:${PG_PORT}/${POSTGRES_DB}?schema=public
  #   volumes:
  #     - ./src:/app/src
  #   depends_on:
  #     - postgres
  #   networks:
  #     - myNet
  #   ports:
  #     - ${PORT}:${PORT}

  postgres:
    container_name: pg-container
    build: ./db
    restart: unless-stopped
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSW}
        - POSTGRES_DB=${POSTGRES_DB}
    volumes:
        - postgres:/var/lib/postgresql/data
    ports:
        - ${PG_PORT}:${PG_PORT}
    networks:
      - myNet
    env_file:
      - .env

volumes:
  postgres:

networks:
  myNet:
    driver: bridge